name: Deploy Site on netlify

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Create local changes
        run: |
          npm install --no-audit --no-fund
          npx tailwind -i app.css -o dist/app.min.css -m
          xcopy index.html dist
          xcopy app.js dist

          pip install -r requirements.txt
          python downloader.py dist

          cd netlify/functions
          npm install node-fetch@3 jsdom -D --no-audit --no-fund
      - name: Deploy
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "dist"
          deploy-message: "${{ github.event.head_commit.message }} (${{ github.event.head_commit.id }}) [Auto Deploy]"
          production-deploy: true
          fails-without-credentials: true
          functions-dir: "netlify/functions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
